// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Samad.Infrastructure.Context;

#nullable disable

namespace Samad.Infrastructure.Migrations
{
    [DbContext(typeof(SamadDbContext))]
    [Migration("20260921060530_UpdateModels")]
    partial class UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Samad.Domain.Entity.CouncilMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CouncilMember");
                });

            modelBuilder.Entity("Samad.Domain.Entity.CouncilReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CouncilMemberId")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Vote")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CouncilMemberId");

                    b.HasIndex("RequestId", "CouncilMemberId")
                        .IsUnique();

                    b.ToTable("CouncilReviews");
                });

            modelBuilder.Entity("Samad.Domain.Entity.CouncilSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CouncilMemberId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CouncilMemberId");

                    b.HasIndex("RequestId", "CouncilMemberId")
                        .IsUnique();

                    b.ToTable("CouncilSignature");
                });

            modelBuilder.Entity("Samad.Domain.Entity.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeadlineAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Urgency")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("DeadlineAt");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Samad.Domain.Entity.RequestCouncilAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("AssignmentType")
                        .HasColumnType("tinyint");

                    b.Property<int>("CouncilMemberId")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CouncilMemberId");

                    b.HasIndex("RequestId", "CouncilMemberId")
                        .IsUnique();

                    b.ToTable("RequestCouncilAssignment");
                });

            modelBuilder.Entity("Samad.Domain.Entity.RequestDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DocumentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)7);

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestDocuments");
                });

            modelBuilder.Entity("Samad.Domain.Entity.RequestStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte?>("FromStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<byte>("ToStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("RequestId", "ChangedAt");

                    b.ToTable("RequestStatusHistory");
                });

            modelBuilder.Entity("Samad.Domain.Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Applicant"
                        },
                        new
                        {
                            Id = 2,
                            Title = "CouncilMember"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Secretary"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Admin"
                        });
                });

            modelBuilder.Entity("Samad.Domain.Entity.SecretaryDecision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Decision")
                        .HasColumnType("tinyint");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("SecretaryId")
                        .HasColumnType("int");

                    b.Property<byte>("Stage")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("SecretaryId");

                    b.HasIndex("RequestId", "Stage", "CreatedAt");

                    b.ToTable("SecretaryDecision");
                });

            modelBuilder.Entity("Samad.Domain.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .IsFixedLength();

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NationalCode")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2000, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2000, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amiraliaghaeibs@gmail.com",
                            FirstName = "Amirali",
                            LastName = "Aghaei",
                            NationalCode = "2581288426",
                            PasswordHash = "AQAAAAIAAYagAAAAEB9aIlLnvh557v9Jn7OQBBTJIIbZC1gA5RVkFD+JCrl65djhtNZWAo2Bn9at/aLkVA==",
                            PhoneNumber = "09120882458",
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("Samad.Domain.Entity.CouncilMember", b =>
                {
                    b.HasOne("Samad.Domain.Entity.User", "User")
                        .WithOne("CouncilMembership")
                        .HasForeignKey("Samad.Domain.Entity.CouncilMember", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Samad.Domain.Entity.CouncilReview", b =>
                {
                    b.HasOne("Samad.Domain.Entity.User", "CouncilMember")
                        .WithMany("MyReviews")
                        .HasForeignKey("CouncilMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Samad.Domain.Entity.Request", "Request")
                        .WithMany("CouncilReviews")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CouncilMember");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Samad.Domain.Entity.CouncilSignature", b =>
                {
                    b.HasOne("Samad.Domain.Entity.User", "CouncilMember")
                        .WithMany()
                        .HasForeignKey("CouncilMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Samad.Domain.Entity.Request", "Request")
                        .WithMany("CouncilSignatures")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CouncilMember");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Samad.Domain.Entity.Request", b =>
                {
                    b.HasOne("Samad.Domain.Entity.User", "Applicant")
                        .WithMany("MyRequests")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("Samad.Domain.Entity.RequestCouncilAssignment", b =>
                {
                    b.HasOne("Samad.Domain.Entity.User", "CouncilMember")
                        .WithMany()
                        .HasForeignKey("CouncilMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Samad.Domain.Entity.Request", "Request")
                        .WithMany("CouncilAssignments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CouncilMember");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Samad.Domain.Entity.RequestDocument", b =>
                {
                    b.HasOne("Samad.Domain.Entity.Request", "Request")
                        .WithMany("Documents")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Samad.Domain.Entity.RequestStatusHistory", b =>
                {
                    b.HasOne("Samad.Domain.Entity.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Samad.Domain.Entity.Request", "Request")
                        .WithMany("StatusHistory")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Samad.Domain.Entity.SecretaryDecision", b =>
                {
                    b.HasOne("Samad.Domain.Entity.Request", "Request")
                        .WithMany("SecretaryDecisions")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Samad.Domain.Entity.User", "Secretary")
                        .WithMany()
                        .HasForeignKey("SecretaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Secretary");
                });

            modelBuilder.Entity("Samad.Domain.Entity.User", b =>
                {
                    b.HasOne("Samad.Domain.Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Samad.Domain.Entity.Request", b =>
                {
                    b.Navigation("CouncilAssignments");

                    b.Navigation("CouncilReviews");

                    b.Navigation("CouncilSignatures");

                    b.Navigation("Documents");

                    b.Navigation("SecretaryDecisions");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Samad.Domain.Entity.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Samad.Domain.Entity.User", b =>
                {
                    b.Navigation("CouncilMembership");

                    b.Navigation("MyRequests");

                    b.Navigation("MyReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
